### ISSUE TITLE
gaugetest ImportError: No module named constants

### ISSUE THREAD

**Issue by jaroslaw-hill** [what-studio/gauge#2]
Hi All,
this time I decided to use the library under xubuntu, but after installation when I was trying to launch gaugetest (the same for other test scripts) the interpreter throw me the error **ImportError: No module named constants**
Any ideas how to fix this?

This is the log

warning: Debugger speedups using cython not found. Run '"/usr/bin/python" "/home/jh/.p2/pool/plugins/org.python.pydev_5.9.2.201708151115/pysrc/setup_cython.py" build_ext --inplace' to build.
pydev debugger: starting (pid: 3395)
Traceback (most recent call last):
  File "/home/jh/.p2/pool/plugins/org.python.pydev_5.9.2.201708151115/pysrc/pydevd.py", line 1621, in <module>
    main()
  File "/home/jh/.p2/pool/plugins/org.python.pydev_5.9.2.201708151115/pysrc/pydevd.py", line 1615, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/jh/.p2/pool/plugins/org.python.pydev_5.9.2.201708151115/pysrc/pydevd.py", line 1022, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/jh/eclipse-workspace/gauge-master/gaugetest.py", line 13, in <module>
    import gauge
  File "/home/jh/eclipse-workspace/gauge-master/gauge/__init__.py", line 15, in <module>
    from gauge.constants import CLAMP, ERROR, inf, OK, ONCE
ImportError: No module named constants

**Comment by sublee** [comment]
Did you compile Cython code?

```console
$ python setup.py build_ext --inplace
```

There should be `gauge/constants.so` which is compiled from `gauge/constants.pyx`.

**Comment by jaroslaw-hill** [comment]
Thanks a lot, now it works,
but when I try to run visualizer.py I got next error that is probably not an installation issue, 
how can I run this visualizer script?

  File "/home/jh/eclipse-workspace/gauge-master/tools/visualizer.py", line 240, in <module>
    main(g, 5)
  File "/home/jh/eclipse-workspace/gauge-master/tools/visualizer.py", line 226, in main
    surf = disp.render(at)
  File "/home/jh/eclipse-workspace/gauge-master/tools/visualizer.py", line 79, in render
    ratio = self.gauge.current(at) / float(self.gauge.max)
AttributeError: 'gauge.core.Gauge' object has no attribute 'current'

**Comment by sublee** [comment]
That is a different bug.  Would you close this issue and open a separate issue?
